### ISSUE TITLE
Format JSON output

### ISSUE THREAD

**Issue by konglor** [Bossmanswift/GENERIC-TEAM#48]

**Comment by Bossmanswift** [comment]
I feel like this is unnecessary because one can easily use enhanced text editors for this. I, for example,  use atom to beautify the output and it looks really great.

**Comment by konglor** [comment]
I use notepad++ and Eclipse IDE, it does not format.
Beautifying the output for you inside the Atom IDE does not beautify the output for everyone, nor formats the JSON file. Using another IDE is not the root solution, IMO.

I'll close this case, since it is expected that we all should know how to format it.
